# Generated by Django 4.2.7 on 2023-11-12 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='time_limit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ChallengeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.challenge')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.requirement')),
            ],
        ),
    ]
