# Generated by Django 4.2.7 on 2023-11-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_challenge_time_limit_challengerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='requirements',
            field=models.ManyToManyField(to='gamification.requirement'),
        ),
    ]
