# Generated by Django 4.2.7 on 2023-11-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_goal_requirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalRequirement',
        ),
    ]
