# Generated by Django 4.2.7 on 2023-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_challenge_requirements_delete_challengerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='reward',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
