# Generated by Django 5.0.3 on 2024-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_challenge_repeatable_challenge_repetition_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='distinct_days',
            field=models.BooleanField(default=False),
        ),
    ]
