# Generated by Django 5.0.3 on 2024-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_requirement_distinct_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
