# Generated by Django 4.2.7 on 2023-11-12 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengehistory',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 22, 37, 20, 437439)),
        ),
    ]
