# Generated by Django 4.2.7 on 2023-11-13 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_challengehistory_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengehistory',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 21, 0, 55, 603606)),
        ),
    ]
