# Generated by Django 4.2.7 on 2023-11-22 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_medication_medicationfrequency'),
        ('core', '0012_alter_challengehistory_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationfrequency',
            name='medication',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='medication_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.medicationfrequency'),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='MedicationFrequency',
        ),
    ]
