# Generated by Django 4.2.7 on 2023-11-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='https://health.xempre.com/static/user.png', max_length=255),
            preserve_default=False,
        ),
    ]
