# Generated by Django 5.0.3 on 2024-04-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code_last_request',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
