# Generated by Django 4.2.7 on 2023-11-06 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('idMeasurement', models.AutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('systolicPressure', models.DecimalField(decimal_places=2, max_digits=3)),
                ('diastolicPressure', models.DecimalField(decimal_places=2, max_digits=3)),
                ('heartRate', models.IntegerField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('bloodOxygen', models.IntegerField(null=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
