# Generated by Django 4.2.7 on 2023-11-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='diastolicPressure',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='systolicPressure',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
