# Generated by Django 4.2.7 on 2023-11-10 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_alter_measurement_diastolicpressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurementDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
