# Generated by Django 4.2.7 on 2023-11-11 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('systolic_pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diastolic_pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heart_rate', models.IntegerField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('blood_oxygen', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
