# Generated by Django 4.2.7 on 2023-11-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='used_recommended_method',
            field=models.BooleanField(default=False),
        ),
    ]
