# Generated by Django 4.2.7 on 2023-11-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_medication_medicationfrequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
