# Generated by Django 4.2.7 on 2023-11-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_medication_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='medicationfrequency',
            name='dose',
            field=models.CharField(max_length=250),
        ),
    ]
