# Generated by Django 5.0.3 on 2024-04-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_medication_description_alter_medication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='comments',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
