# Generated by Django 5.0.3 on 2024-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_measurement_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=1024, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
