# Generated by Django 5.0.3 on 2024-04-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_rename_articles_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
