# Generated by Django 5.0.3 on 2024-04-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationfrequency',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
