# Generated by Django 5.0.3 on 2024-04-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_alter_medicationfrequency_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationfrequency',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationfrequency',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationfrequency',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationfrequency',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationfrequency',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationfrequency',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationfrequency',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
